question_data = [
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "text": "Hidden in the files for &quot;Mario Kart Arcade GP&quot; is a picture of the Beslan school hostage crisis.",
     "answer": "True",
     "wrongs": ["False"]
     },
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "text": "There are 2 player roles in Trouble in Terrorist Town.", "answer": "False",
     "wrongs": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "text": "The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.",
     "answer": "False", "wrongs": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "text": "In Pok&eacute;mon, Arbok evolves into Seviper.", "answer": "False",
     "wrongs": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "text": "The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.",
     "answer": "True", "wrongs": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "text": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.", "answer": "False",
     "wrongs": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "text": "Activision created Battlefield 1.", "answer": "False", "wrongs": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "text": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
     "answer": "True", "wrongs": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "text": "The game Garry&#039;s Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
     "answer": "True", "wrongs": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "text": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.", "answer": "False",
     "wrongs": ["True"]}
]
